version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: smart-shopper-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=smart-shopper
    networks:
      - smart-shopper-network

volumes:
  mongodb_data:
    name: smart-shopper-mongodb-data

networks:
  smart-shopper-network:
    name: smart-shopper-network 